
//#define BIO_1
#define ICP_TSD
//#define TSD_GLB
#define ICP_7060
#define ICP_7041
#define RTU_MVD
#define ICP_7017C
//#define RTU_Delta
#define RTU_Delta_C
//#define RTU_ComSK
//#define EKD_800
#define RTU_OFP

//14.06.2021 YN           //контроль плотности при наливе
#define DENSITY_CONTROL     //для отключения закоментировать

//20.08.2021 YN           //контроль разряжения при наливе
#define UNDERPRESSURE       //для отключения закоментировать

//18.11.2021 YN
#define weightedAverageTemperature //средневзвешенная температура 
                                    //закоментировать если не надо
